name = "bildung-in-bildern"
compatibility_date = "2026-03-27"
pages_build_output_dir = "out"

[[d1_databases]]
binding = "DB"
database_name = "bib-analytics"
database_id = "b41cf4b0-6217-4da1-a9e8-e11568e504a7"
